# Generated by Django 5.0.4 on 2024-04-07 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('building_name', models.CharField(max_length=20)),
                ('address_number', models.IntegerField()),
                ('address_street', models.CharField(max_length=20)),
                ('address_city', models.CharField(max_length=20)),
                ('address_state', models.CharField(max_length=5)),
                ('address_zip_code', models.CharField(max_length=5)),
                ('year_built', models.IntegerField()),
            ],
            options={
                'unique_together': {('company_name', 'building_name')},
            },
        ),
        migrations.CreateModel(
            name='ApartmentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=10)),
                ('monthly_rent', models.IntegerField()),
                ('square_footage', models.IntegerField()),
                ('available_date_for_move_in', models.DateField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.apartmentbuilding')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.amenities')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.apartmentunit')),
            ],
        ),
        migrations.CreateModel(
            name='PetPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=50)),
                ('pet_size', models.CharField(max_length=20)),
                ('is_allowed', models.BooleanField()),
                ('registration_fee', models.IntegerField(blank=True, null=True)),
                ('monthly_fee', models.IntegerField(blank=True, null=True)),
                ('apartment_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.apartmentbuilding')),
            ],
            options={
                'unique_together': {('apartment_building', 'pet_type', 'pet_size')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('square_footage', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.apartmentunit')),
            ],
            options={
                'unique_together': {('name', 'unit')},
            },
        ),
    ]
