# Generated by Django 5.0.4 on 2024-04-07 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField()),
                ('waiting_list', models.IntegerField()),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.amenities')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.apartmentbuilding')),
            ],
            options={
                'unique_together': {('amenity', 'building')},
            },
        ),
    ]
