# Generated by Django 5.0.4 on 2024-04-24 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_provides'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='provides',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='provides',
            name='amenity',
        ),
        migrations.RemoveField(
            model_name='provides',
            name='building',
        ),
        migrations.DeleteModel(
            name='PetPolicy',
        ),
        migrations.DeleteModel(
            name='Provides',
        ),
    ]
