# Generated by Django 5.0.4 on 2024-04-24 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_alter_provides_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentamenities',
            name='amenity',
        ),
        migrations.RemoveField(
            model_name='apartmentamenities',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Amenities',
        ),
        migrations.DeleteModel(
            name='ApartmentAmenities',
        ),
    ]
