# Generated by Django 5.0.4 on 2024-04-24 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_remove_apartmentamenities_amenity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
