# Generated by Django 5.0.4 on 2024-04-24 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_delete_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentunit',
            name='building',
        ),
        migrations.DeleteModel(
            name='ApartmentBuilding',
        ),
        migrations.DeleteModel(
            name='ApartmentUnit',
        ),
    ]
