# Generated by Django 5.0.4 on 2024-04-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='is_favourited',
            field=models.BooleanField(default=False),
        ),
    ]
