# Generated by Django 5.0.4 on 2024-04-24 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interest',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_interests', to=settings.AUTH_USER_MODEL),
        ),
    ]
