# Generated by Django 5.0.4 on 2024-04-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='is_favourited',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='likes',
        ),
    ]
