# Generated by Django 5.0.4 on 2024-04-24 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_post', '0005_initial'),
        ('home', '0003_interest_dislikes_interest_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_post.apartmentunit'),
        ),
    ]
