# Generated by Django 5.0.4 on 2024-04-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_interest_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
    ]
