# Generated by Django 5.0.4 on 2024-04-28 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_post', '0005_initial'),
        ('home', '0005_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='interest',
        ),
        migrations.AddField(
            model_name='favorite',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unit_favorites', to='add_post.apartmentunit'),
        ),
    ]
