# Generated by Django 5.0.4 on 2024-04-28 20:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_post', '0005_initial'),
        ('home', '0006_remove_favorite_interest_favorite_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'unit')},
        ),
    ]
