# Generated by Django 5.0.4 on 2024-04-24 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='name',
            new_name='pet_name',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='size',
            new_name='pet_size',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='type',
            new_name='pet_type',
        ),
        migrations.AlterUniqueTogether(
            name='pet',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pet',
            unique_together={('pet_name', 'pet_type', 'owner')},
        ),
    ]
