# Generated by Django 5.0.4 on 2024-04-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_post', '0003_delete_amenity_delete_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentunit',
            name='company',
        ),
        migrations.DeleteModel(
            name='ApartmentBuilding',
        ),
        migrations.DeleteModel(
            name='ApartmentUnit',
        ),
    ]
